# CPython test project, check against Nuitka develop.
language: python

matrix:
  include:
    - os: linux
      python: 3.7
      dist: xenial
      sudo: required
      cache: ccache

# disable submodules from git
git:
  submodules: false
# commands to install dependencies
install:
  - pip install -U "https://github.com/Nuitka/Nuitka/archive/factory.zip"
# commands to run tests
script:
  - env NUITKA_TEST_INSTALLED=1 python run_all.py search
